export const subjectMappings: { [key: string]: string[] } = {
    // Music
    music: ["music"],
    bach: ["music"],
    beethoven: ["music"],
    mozart: ["music"],
    chopin: ["music"],
    classical: ["music"],
    jazz: ["music"],
    rock: ["music"],
    pop: ["music"],
    hiphop: ["music"],
    opera: ["music"],
    symphony: ["music"],
    concerto: ["music"],
    sonata: ["music"],
    blues: ["music"],
    gospel: ["music"],
    folk: ["music"],
    country: ["music"],
    reggae: ["music"],

    // Art
    art: ["art"],
    picasso: ["art"],
    dali: ["art"],
    "van gogh": ["art"],
    rembrandt: ["art"],
    monet: ["art"],
    painting: ["art"],
    sculpture: ["art"],
    architecture: ["art", "design and construction management"],
    photography: ["art"],
    impressionism: ["art"],
    cubism: ["art"],
    surrealism: ["art"],
    modernism: ["art"],

    // History
    history: ["history"],
    "civil war": ["history"],
    "world war 2": ["history"],
    "world war 1": ["history"],
    revolution: ["history", "political science"],
    ancient: ["history"],
    rome: ["history"],
    greece: ["history"],
    egypt: ["history"],
    medieval: ["history"],
    renaissance: ["history"],
    "cold war": ["history", "political science"],
    vietnam: ["history"],
    colonialism: ["history"],
    imperialism: ["history"],

    // Literature
    literature: ["english"],
    shakespeare: ["english", "theatre"],
    dickens: ["english"],
    austen: ["english"],
    twain: ["english"],
    hemingway: ["english"],
    poetry: ["english"],
    fiction: ["english"],
    novel: ["english"],
    drama: ["theatre"],
    tragedy: ["english", "theatre"],
    comedy: ["english", "theatre"],
    romanticism: ["english", "art"],

    // Science
    science: ["biology", "chemistry", "physics", "geology"],
    biology: ["biology"],
    chemistry: ["chemistry"],
    physics: ["physics"],
    geology: ["geology"],
    astronomy: ["physics"],
    evolution: ["biology"],
    genetics: ["biology"],
    quantum: ["physics"],
    ecology: ["biology"],
    environment: ["geology", "biology"],
    climate: ["geology", "physics"],
    weather: ["geology"],

    // Business & Economics
    business: ["business management", "economics", "finance", "marketing"],
    economics: ["economics"],
    finance: ["finance"],
    marketing: ["marketing"],
    management: ["business management"],
    investment: ["finance"],
    stocks: ["finance"],
    accounting: ["accounting"],
    trade: ["economics"],
    commerce: ["business management"],
    entrepreneurship: ["business management"],

    // Technology
    technology: ["computer science and electrical engineering", "computer information technology"],
    programming: ["computer science and electrical engineering"],
    code: ["computer science and electrical engineering"],
    software: ["computer science and electrical engineering"],
    hardware: ["computer science and electrical engineering"],
    ai: ["computer science and electrical engineering"],
    "machine learning": ["computer science and electrical engineering"],
    database: ["computer information technology"],
    network: ["computer information technology"],
    internet: ["computer information technology"],
    cybersecurity: ["computer information technology"],

    // Health & Medicine
    health: ["health services", "nursing"],
    medicine: ["health services", "nursing"],
    nursing: ["nursing"],
    doctor: ["health services"],
    hospital: ["health services"],
    disease: ["health services"],
    cancer: ["health services"],
    heart: ["health services"],
    psychology: ["psychology"],
    therapy: ["psychology", "sociology and social work"],
    mental: ["psychology"],
    psychiatry: ["psychology"],
    nutrition: ["health services", "home and family"],
    wellness: ["health services"],

    // Social Sciences
    sociology: ["sociology and social work"],
    anthropology: ["sociology and social work"],
    "political science": ["political science"],
    government: ["political science"],
    law: ["political science"],
    crime: ["political science", "sociology and social work"],
    justice: ["political science", "sociology and social work"],
    politics: ["political science"],
    democracy: ["political science"],
    rights: ["political science", "sociology and social work"],

    // Other
    food: ["animal and food science", "home and family"],
    cooking: ["home and family"],
    gardening: ["applied plant science"],
    plants: ["applied plant science"],
    animals: ["animal and food science"],
    film: ["theatre"],
    movie: ["theatre"],
    theatre: ["theatre"],
    dance: ["dance"],
    sports: ["human performance and recreation"],
    exercise: ["human performance and recreation"],
    olympics: ["human performance and recreation"],
    philosophy: ["humanities and philosophy"],
    religion: ["religious education"],
    bible: ["religious education"],
    christianity: ["religious education"],
    islam: ["religious education"],
    judaism: ["religious education"],
    buddhism: ["religious education"],
    hinduism: ["religious education"],
    mythology: ["humanities and philosophy"],
    education: ["teacher education"],
    teaching: ["teacher education"],
    learning: ["teacher education"],
    family: ["home and family", "family history"],
    genealogy: ["family history"],
    marriage: ["home and family"],
    children: ["home and family", "teacher education"],
    women: ["sociology and social work", "history"],
    gender: ["sociology and social work"],
    race: ["sociology and social work", "history"],
    maps: ["geography"],
    geography: ["geography"],
    travel: ["geography"],
    transportation: ["mechanical & civil engineering"],
    engineering: ["mechanical & civil engineering", "automotive engineering / technology", "computer science and electrical engineering"],
    automotive: ["automotive engineering / technology"],
    cars: ["automotive engineering / technology"],
    construction: ["design and construction management"],
    design: ["design and construction management", "interior design", "art"],
    interior: ["interior design"],
    fashion: ["home and family"],
    clothing: ["home and family"],
    communication: ["communications"],
    media: ["communications"],
    journalism: ["communications"],
    writing: ["english"],
    language: ["languages and international studies"],
    spanish: ["languages and international studies"],
    french: ["languages and international studies"],
    german: ["languages and international studies"],
    chinese: ["languages and international studies"],
    japanese: ["languages and international studies"],
    math: ["mathematics"],
    mathematics: ["mathematics"],
    statistics: ["mathematics"],
    algebra: ["mathematics"],
    calculus: ["mathematics"],
    geometry: ["mathematics"],
};